language: go
services:
- mysql
- postgres
- redis-server
addons:
  postgresql: '9.4'
go:
#- '1.7'
- '1.8'
#- '1.9'
- tip
go_import_path: github.com/stellar/go
install:
- wget https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-linux-amd64.tar.gz
- tar -xzvf glide-v0.12.3-linux-amd64.tar.gz
- cp linux-amd64/glide $GOPATH/bin
script:
- glide install
- "./support/scripts/run_tests"
before_deploy:
- go run ./support/scripts/build_release_artifacts/main.go
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: Uhx8H2RFNsJ9GknDItSwhMOl5K3HTGNjifJwkLUiRio4JH4PzrkHDOzCOpEzrboviVF+Rch9VsC7HchIY2uyqeB9UW63dCMPeaYSs7rfNCmW8bTcGydeVOe0HV18mpM/4yPy/gsw5Zq+eGq7+p9NZtwkOHeQ/YtoSFcWbQQYs3CPZpBUP95KW1fGTn8OIW6nKkVA0Kyr6aXJFZB9AHIg24R9l2uraHdjg5EUJJO/4yR0GWC1pLTfUCqUt9mXPeGSQOhhvR+pCKSljY3pB6oex2hKH04u3U1iRzOBuKMPmMrcyJDzvVRkCaCn+0LPGZ3vgDDcDdcqYxEk1a1n27wzjqYlDeH4xaYTZGpB18LiX6MAm84+iviL5JILIMQ4NcqVNB2L37zl1UW+BMQUSH6+zQknHkGcOImU984PEdrhCM2uvknvp0+IGXdpyv9WwztzxhJOz6PAE1aA3O+BI1xuSft6sGY07Z0Q9iKO/uCWIHbsfLso16kIubiHzwjSAz90tbCc8VcR4EFeVqEoWm9QwRP0v6pclWMhj9bq3Oye1gKrSCwWPXCg8mRFCCuXgr4dev7I+vKcx43oIddgcx6vIROMYsgX/0gInBrkNxZw3Gu1YUXe1fuNvmCZWSlaWrO+9XWnFItnLs2ypnQjlguKzxgqmfqR0eXmMYBQrH18sxU=
deploy:
  provider: releases
  api_key:
    secure: q/CrylkCtCRGeFW/bqi4nmthYiQxDw4tp5RzZrlh/50ydDVmckrHC8XAqTMs7cIAKxcdPr46cqMCOdl5rtCOzIftLUMOi8b5e4o29k5EBPS+hRuMZDR+yoDYT8k6sJh2DIbSZiwc+zizWCZ8lumomJb2IXlaAxEzjp2HPKGMGzNyoSEuDZg1elKD7jHTbcXVVjfjKu9hC8gtVCsPmc4atCEbY3ZpV4B2fGFGTR8qxSr2AtJx78mVQFfjzsDeFp1SsC8h8oYcfeRTcvTdVW9idCcOtLQ7BOsH916WUhRdokLYAgLBl3Qsp0wgJeFPaZXNzShtZ3hx6pKUmfWxRA+j/28veqGE9B9iVF3mvVF1VO5iYxWXtn23ukd8v4HoGLqa07MBVgupDN1i7IWvIywzRsB3aQ5JHU+8BrbAS49nWJiDPzuq4Cucnif5a0cVMVLmnuEu5blnKgN9IR/BGOZcNISpzU0W3fiSyU+BPdIr5h090IkHOiFYE6QxFNvOY9Aqu/cPb0sxccL0eMGZCbCUKLIu6HjzP+XmNRWQLrR/L0hE/YCyrTIBNZgLP7R4qtjhg7UEP/zoNcr82hHQVUFR/LfInwXnjyBb6TJqze4kvjarvpryQmR55kf4Kbl8ogZtjXE50F/RJU8aYLtf1wMGdi6kcllNd+bsSEMSYeRt7Wo=
  file: dist/*
  on:
    branch: master-debug-build
